
-- Creación de tabla SIACON

CREATE TABLE SIACON_AGRO (
	id integer PRIMARY KEY,
    anio integer,
    id_ddr integer,
    id_cader integer,
    id_estado integer,
    -- nom_estado varchar(255),
    id_municipio integer,
    -- nom_municipio varchar(255),
    id_ciclo integer,
    -- nom_ciclo varchar(255), 
    id_modalidad  integer, 
    -- nom_modalidad varchar(255), 
    id_cultivo integer, 
    -- nom_cultivo varchar(255),
    cultivo varchar(255),
    id_variedad integer, 
    -- variedad varchar(255),
    nom_variedad varchar(255),
    id_unidadmedida integer,
    -- nom_unidad varchar(255),
    nom_corto varchar(255),
    id_tipoagricultura integer,
    -- nom_tipoagricultura varchar(255),
    id_tipoproduccion integer,
    -- nom_tipoproduccion varchar(255),
    id_mercado integer,
    -- nom_mercado varchar(255), 
    sembrada numeric,
    cosechada numeric,
    siniestrada numeric,
    volumenproduccion numeric,
    valorproduccion numeric,
    rendimiento numeric,
    preciomediorural numeric
);